#!/usr/bin/env bash
#
# linux-backup-system — restore-verified multi-layer Linux backups for every distro and boot layout
# https://github.com/doug445/linux-backup-system
#
# Copyright (c) 2026 William MacKinnon <spilled-bowline0j@icloud.com>
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# backup-common.sh — shared library for the linux-backup-system fleet tooling.
#
# Sourced by borg-backup.sh, backintime-backup.sh, the Timeshift wrapper, the
# restore scripts and the drive-attach unit. Everything host-specific lives in
# /etc/backup-system.conf (generated by deploy.sh); every path that depends on
# the machine's disk or boot layout is DERIVED AT RUN TIME here, never hardcoded,
# so one copy of every script runs unchanged on every distro and every boot
# layout (systemd-boot/GRUB, UKI/standard, encrypted or plain /boot).
#
# This file only defines variables and functions; it starts nothing.

# Version of the suite. Printed in every detection dump and by backup-diag.sh so
# a report can be tied to a release; bump with each tag.
# shellcheck disable=SC2034  # read by every script that sources this file
BX_VERSION="3.6.3"

# ---------------------------------------------------------------------------
# Config: load /etc/backup-system.conf, then fill any gap with a safe default.
# ---------------------------------------------------------------------------
BX_CONFIG="${BX_CONFIG:-/etc/backup-system.conf}"

# Precedence: environment > /etc/backup-system.conf > built-in default, so a
# one-off override works from the shell (KEEP=2 timeshift-backup.sh --prune-only)
# and from a unit's Environment= line, without editing the host config.
BX_CONFIG_VARS="BACKUP_MOUNT BORG_REPO BACKUP_FS_UUID BACKUP_LUKS_UUID BACKUP_KEYFILE BACKUP_MOUNT_OPTS SCHEDULE_MODE BACKUP_EXTRA_SOURCES KEEP MIN_KEEP MIN_FREE_PCT MIN_FREE_GIB CAPACITY_HEADROOM_PCT CAPACITY_RECOMMEND_X"

bx_load_config() {
    local _v _env=()
    for _v in $BX_CONFIG_VARS; do [ -n "${!_v+x}" ] && _env+=("$_v=${!_v}"); done
    # shellcheck disable=SC1090
    [ -r "$BX_CONFIG" ] && . "$BX_CONFIG"
    for _v in "${_env[@]}"; do declare -g "$_v"; done

    BACKUP_MOUNT="${BACKUP_MOUNT:-/mnt/backup}"
    BORG_REPO="${BORG_REPO:-$BACKUP_MOUNT/borg-backup}"
    BACKUP_FS_UUID="${BACKUP_FS_UUID:-}"       # empty = skip the wrong-drive guard
    BACKUP_LUKS_UUID="${BACKUP_LUKS_UUID:-}"   # for unlock-on-attach only
    BACKUP_KEYFILE="${BACKUP_KEYFILE:-}"       # for unlock-on-attach only
    BACKUP_MOUNT_OPTS="${BACKUP_MOUNT_OPTS:-}" # mount -o opts for the drive (fs-specific)
    SCHEDULE_MODE="${SCHEDULE_MODE:-adhoc}"    # adhoc | scheduled
    BACKUP_EXTRA_SOURCES="${BACKUP_EXTRA_SOURCES:-}"

    # Retention (all layers): count-based + free-space based, never time-based.
    KEEP="${KEEP:-10}"                  # normal count to keep, any age
    MIN_KEEP="${MIN_KEEP:-3}"           # hard floor, never prune below this
    MIN_FREE_PCT="${MIN_FREE_PCT:-10}"  # keep at least this % of the drive free
    MIN_FREE_GIB="${MIN_FREE_GIB:-0}"   # and at least this many GiB free (0 = ignore)

    # Capacity: the drive must hold one full copy of everything in the backup
    # sources plus this much spare room, or the suite refuses to use it; and
    # it should be at least CAPACITY_RECOMMEND_X times the total size of the
    # Linux filesystems it backs up (not the whole disk).
    CAPACITY_HEADROOM_PCT="${CAPACITY_HEADROOM_PCT:-20}"
    CAPACITY_RECOMMEND_X="${CAPACITY_RECOMMEND_X:-2}"
}

# ---------------------------------------------------------------------------
# Free space on the backup drive.
# ---------------------------------------------------------------------------
bx_free_pct() { local u; u=$(df --output=pcent "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9'); echo $(( 100 - ${u:-100} )); }
bx_free_gib() { local a; a=$(df --output=avail "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9'); echo $(( ${a:-0} / 1024 / 1024 )); }
bx_space_low() { [ "$(bx_free_pct)" -lt "$MIN_FREE_PCT" ] || [ "$(bx_free_gib)" -lt "$MIN_FREE_GIB" ]; }

# ---------------------------------------------------------------------------
# Capacity: is the backup drive big enough for this machine?
#
# Two thresholds. The FLOOR is measured against what is actually on the
# machine: the used bytes of every filesystem in the backup sources, plus
# CAPACITY_HEADROOM_PCT spare room. A drive below the floor cannot hold even
# one full copy and is refused — by deploy.sh before it formats or adopts one,
# and by every backup script before it writes. The RECOMMENDATION is measured
# against the Linux system: CAPACITY_RECOMMEND_X times the total size of the
# filesystems in the backup sources (root, /home, /boot, the ESP — each
# counted once), so the drive has room for many generations of every layer.
# Not the whole disk: on a dual-boot or Apple Silicon machine most of the disk
# belongs to another OS and is never backed up. Below that is a warning, not
# a stop.
# ---------------------------------------------------------------------------
bx_human_bytes() { # bx_human_bytes BYTES -> "1.8 TiB"
    local b="${1:-0}"
    awk -v b="$b" 'BEGIN{ split("B KiB MiB GiB TiB PiB",u," "); i=1; v=b+0;
        while (v>=1024 && i<6) { v/=1024; i++ }
        if (i==1) printf "%d %s", v, u[i]; else printf "%.1f %s", v, u[i] }'
}

# The whole disk a block device (partition, LUKS mapper, LV) ultimately sits on.
bx_disk_of() { # bx_disk_of /dev/xxx -> /dev/nvme0n1
    local d kn pk sl
    d=$(readlink -f "$1" 2>/dev/null) || return 1; kn=$(basename "$d")
    while :; do
        # device-mapper (LUKS, LVM): the parent is a sysfs slave, not PKNAME
        sl=$(ls "/sys/block/$kn/slaves" 2>/dev/null | head -1 || true)
        if [ -n "$sl" ]; then kn="$sl"; continue; fi
        # partition -> its disk
        pk=$(lsblk -dno PKNAME "/dev/$kn" 2>/dev/null | head -1 || true)
        if [ -n "$pk" ]; then kn="$pk"; continue; fi
        break
    done
    [ -b "/dev/$kn" ] && echo "/dev/$kn"
}

# Sum of one df column (used | size) across every filesystem in the backup
# sources, each counted once (btrfs subvolumes of one filesystem share one
# figure). This is the Linux portion of the machine — what a backup copies and
# what it would restore onto — not the whole disk.
_bx_sources_sum() { # _bx_sources_sum used|size
    local col="$1" m src seen=" " total=0 v
    while read -r m; do
        [ -n "$m" ] || continue
        src=$(findmnt -no SOURCE --target "$m" 2>/dev/null | sed 's/\[.*//' || true)
        [ -n "$src" ] || continue
        case "$seen" in *" $src "*) continue ;; esac
        seen="$seen$src "
        v=$(df -B1 --output="$col" "$m" 2>/dev/null | tail -1 | tr -dc '0-9')
        total=$(( total + ${v:-0} ))
    done < <(bx_backup_sources)
    echo "$total"
}
bx_sources_used_bytes()  { _bx_sources_sum used; }
bx_sources_total_bytes() { _bx_sources_sum size; }

# Size in bytes of the disk the root filesystem lives on (0 if unresolvable).
# Informational — the capacity policy deliberately does NOT use it.
bx_system_disk_bytes() {
    local src disk
    src=$(findmnt -no SOURCE --target / 2>/dev/null | sed 's/\[.*//' || true)
    disk=$(bx_disk_of "${src:-/dev/null}" 2>/dev/null || true)
    [ -n "$disk" ] && lsblk -dnbo SIZE "$disk" 2>/dev/null | head -1 || echo 0
}

# bx_capacity_verdict DRIVE_BYTES USED_BYTES LINUX_TOTAL_BYTES
#   -> "refuse|warn|ok FLOOR RECOMMENDED"  (pure arithmetic; fixture-tested)
bx_capacity_verdict() {
    local drive="${1:-0}" used="${2:-0}" linux="${3:-0}" floor rec v
    floor=$(( used + used * ${CAPACITY_HEADROOM_PCT:-20} / 100 ))
    rec=$(( linux * ${CAPACITY_RECOMMEND_X:-2} ))
    if   [ "$drive" -lt "$floor" ]; then v=refuse
    elif [ "$linux" -gt 0 ] && [ "$drive" -lt "$rec" ]; then v=warn
    else v=ok; fi
    echo "$v $floor $rec"
}

# bx_check_backup_capacity [DRIVE_BYTES] — one line of verdict for the drive
# mounted at BACKUP_MOUNT (or a candidate disk's size in bytes). Returns 1 on
# refuse, 0 otherwise; the line explains either way.
bx_check_backup_capacity() {
    local drive="${1:-}" used linux v floor rec
    if [ -z "$drive" ]; then
        drive=$(df -B1 --output=size "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9')
        [ -n "$drive" ] || { echo "capacity: $BACKUP_MOUNT is not mounted — cannot size it"; return 1; }
    fi
    used=$(bx_sources_used_bytes); linux=$(bx_sources_total_bytes)
    read -r v floor rec < <(bx_capacity_verdict "$drive" "$used" "$linux")
    case "$v" in
        refuse) echo "capacity: REFUSED — drive holds $(bx_human_bytes "$drive"), but a full backup of $(bx_human_bytes "$used") plus ${CAPACITY_HEADROOM_PCT}% spare needs $(bx_human_bytes "$floor")$([ "$linux" -gt 0 ] && echo "; recommended: ${CAPACITY_RECOMMEND_X}x the $(bx_human_bytes "$linux") of Linux filesystems = $(bx_human_bytes "$rec")")"; return 1 ;;
        warn)   echo "capacity: OK but small — drive $(bx_human_bytes "$drive") holds the $(bx_human_bytes "$used") of data (floor $(bx_human_bytes "$floor")); recommended ${CAPACITY_RECOMMEND_X}x the $(bx_human_bytes "$linux") of Linux filesystems = $(bx_human_bytes "$rec")" ;;
        *)      echo "capacity: OK — drive $(bx_human_bytes "$drive") for $(bx_human_bytes "$used") of data (floor $(bx_human_bytes "$floor")$([ "$linux" -gt 0 ] && echo ", recommended $(bx_human_bytes "$rec") = ${CAPACITY_RECOMMEND_X}x the Linux filesystems"))" ;;
    esac
    return 0
}

# ---------------------------------------------------------------------------
# Filesystem / layout detection.
# ---------------------------------------------------------------------------
bx_root_fstype() { findmnt -no FSTYPE / 2>/dev/null; }
bx_is_btrfs()    { [ "$(bx_root_fstype)" = btrfs ]; }

# The local-snapshot / replica layer this host should use:
#   btrfs -> "btrfs" (send/receive replicas, handled in borg-backup.sh)
#   else  -> "timeshift" (rsync snapshots) if timeshift is installed, else "none"
bx_snapshot_engine() {
    if bx_is_btrfs; then echo btrfs
    elif command -v timeshift >/dev/null 2>&1; then echo timeshift
    else echo none; fi
}

# Absolute source paths to feed a file-level backup (borg / BIT). Always "/",
# plus every SEPARATE on-disk mount that a bootable restore needs: a distinct
# /home, /boot, and the ESP wherever it lives (/efi or /boot/efi). A /boot that
# is just a directory on root is already inside "/" and is not listed again.
# btrfs subvolumes have distinct st_dev, so a separate /home must be listed for
# borg --one-file-system to descend into it. Extra mounts can be added via
# BACKUP_EXTRA_SOURCES in the config.
bx_backup_sources() {
    echo /
    local m
    for m in /home /boot /boot/efi /efi /boot/firmware $BACKUP_EXTRA_SOURCES; do
        [ "$m" = / ] && continue
        mountpoint -q "$m" 2>/dev/null && echo "$m"
    done | sort -u
}

# The boot-firmware partition for this host — the ESP on UEFI machines, the
# vfat firmware partition on a Raspberry Pi — from live mounts then fstab, so a
# declared-but-unmounted one is still found. Empty on legacy BIOS. These are
# the ONLY paths the suite recognises; a new layout is added here and in the
# matching lists in backup-verify.sh and restore-rebuild-boot.sh.
BX_ESP_PATHS='/efi|/boot/efi|/boot/firmware'
bx_esp_mount() {
    { findmnt -rno TARGET,FSTYPE 2>/dev/null | awk '$2=="vfat"{print $1}'
      awk '$1 !~ /^#/ && $3=="vfat"{print $2}' /etc/fstab 2>/dev/null
    } | grep -xE "$BX_ESP_PATHS" | head -1
}

# Raspberry Pi firmware boot: no UEFI, no GRUB, no systemd-boot. The SoC's
# firmware reads config.txt / cmdline.txt / kernel*.img from a vfat partition
# (/boot/firmware on Raspberry Pi OS bookworm+, /boot before). Recognised by
# config.txt in that partition on a machine without EFI. UNTESTED ON METAL.
bx_pi_firmware_boot() {
    [ -d /sys/firmware/efi ] && return 1
    [ -f "${BX_PI_FW:-/boot/firmware}/config.txt" ] || [ -f /boot/config.txt ]
}

# Classify an archive/snapshot listing (paths relative to the root, one per
# line) by what would let it boot. Prints: uki kern gcfg sdb pifw — counts of
# UKIs, plain kernels, grub.cfg files, systemd-boot entries, and Raspberry Pi
# firmware config files. Plain kernels include the kernel-install Type #1
# layout, <esp>/<machine-id>/<version>/linux, which systemd-boot without UKIs
# uses on Fedora, Debian and Arch when the ESP is /efi or XBOOTLDR is /boot. Only boot/ and efi/ are considered: /usr/lib/modules
# keeps a vmlinuz copy on Fedora and would satisfy a root-only archive.
# The path segment between boot/|efi/ and the file is optional: with the ESP
# at /efi a UKI lists as efi/EFI/Linux/x.efi and an entry as
# efi/loader/entries/x.conf, with nothing in between — the old patterns
# required a directory there and missed every systemd-boot host with /efi.
bx_boot_listing_counts() { # bx_boot_listing_counts LISTING_FILE
    local f="$1"
    printf '%s %s %s %s %s\n' \
        "$(grep -icE '^(boot|efi)/(.*/)?EFI/Linux/.*\.efi$' "$f")" \
        "$(grep -cE '^(boot|efi)/(.*/)?(vmlinuz|vmlinux|Image|kernel)(-|$)|^(boot|efi)/[0-9a-f]{32}/[^/]+/linux$|^boot/(firmware/)?kernel[0-9_a-z]*\.img$' "$f")" \
        "$(grep -icE '^(boot|efi)/(.*/)?grub\.cfg$' "$f")" \
        "$(grep -icE '^(boot|efi)/(.*/)?loader/(loader\.conf|entries/.+\.conf)$' "$f")" \
        "$(grep -cE '^boot/(firmware/)?(config|cmdline)\.txt$' "$f")"
}

# Is /boot its own filesystem (vs a directory on root)?
bx_boot_is_mount() { mountpoint -q /boot 2>/dev/null; }

# ---------------------------------------------------------------------------
# Is the configured drive physically here? A yanked LUKS drive leaves its
# mapper node, the filesystem UUID link inside it, and the mount all in place;
# only the LUKS partition's own by-uuid link (or, on a plain drive, the
# filesystem's) disappears. Test that, never the mapper or the mount.
# ---------------------------------------------------------------------------
bx_backup_drive_present() {
    if [ -n "${BACKUP_LUKS_UUID:-}" ]; then [ -e "/dev/disk/by-uuid/$BACKUP_LUKS_UUID" ]
    elif [ -n "${BACKUP_FS_UUID:-}" ]; then [ -e "/dev/disk/by-uuid/$BACKUP_FS_UUID" ]
    else return 1; fi
}

# Does a block device still rest on real hardware? A device-mapper node (LUKS,
# LVM) outlives a yanked disk; what disappears is its sysfs slave link. Walk
# the slave chain down to a non-dm device and require one to exist. Reads
# sysfs only, so it works unprivileged.
bx_dev_is_live() { # bx_dev_is_live /dev/xxx
    local dev="$1" node kn s
    [ -e "$dev" ] || return 1
    node=$(readlink -f "$dev" 2>/dev/null || true); kn=$(basename "${node:-$dev}")
    if [ -d "/sys/block/$kn/slaves" ]; then
        for s in "/sys/block/$kn/slaves"/*; do
            [ -e "$s" ] || continue
            bx_dev_is_live "/dev/$(basename "$s")" && return 0
        done
        return 1     # a dm device with no live slave: its disk is gone
    fi
    [ -b "$node" ] && { [ -d "/sys/class/block/$kn" ] || [ -d "/sys/block/$kn" ]; }
}

# Is MOUNT a mount whose backing block device still exists? A dead mount (drive
# unplugged) still answers `mountpoint -q` yes; this does not.
bx_mount_is_live() { # bx_mount_is_live MOUNT
    local m="$1" src
    mountpoint -q "$m" 2>/dev/null || return 1
    src=$(findmnt -no SOURCE --target "$m" 2>/dev/null | sed 's/\[.*//' || true)
    [ -n "$src" ] || return 1
    bx_dev_is_live "$src"
}

# ---------------------------------------------------------------------------
# Wrong-drive guard: refuse to write to a drive whose fs UUID is not the one the
# config pins, or whose backing device is gone (a yanked drive leaves a mount
# that looks mounted and swallows writes). A no-op on the UUID when
# BACKUP_FS_UUID is empty (unconfigured). Returns non-zero with the reason.
# ---------------------------------------------------------------------------
bx_check_backup_drive() {
    mountpoint -q "$BACKUP_MOUNT" 2>/dev/null || { echo "backup mount $BACKUP_MOUNT is not mounted"; return 1; }
    bx_mount_is_live "$BACKUP_MOUNT" || { echo "backup mount $BACKUP_MOUNT is dead: its device is gone (drive unplugged?) — run borg-backup-drive-detach.sh"; return 1; }
    [ -n "$BACKUP_FS_UUID" ] || return 0
    local actual; actual=$(findmnt -n -o UUID --target "$BACKUP_MOUNT" 2>/dev/null)
    if [ "$actual" != "$BACKUP_FS_UUID" ]; then
        echo "wrong drive at $BACKUP_MOUNT: expected fs UUID $BACKUP_FS_UUID, found ${actual:-<none>}"
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Dependencies: identify missing commands up front and install them, rather
# than letting a tool fail silently mid-run. Distro-family aware.
# ---------------------------------------------------------------------------
bx_distro_family() {
    local ID="" ID_LIKE=""
    # BX_OS_RELEASE lets the fixture test feed synthetic os-release files.
    # shellcheck disable=SC1090,SC1091
    [ -r "${BX_OS_RELEASE:-/etc/os-release}" ] && . "${BX_OS_RELEASE:-/etc/os-release}"
    case " ${ID:-} ${ID_LIKE:-} " in
        *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*) echo debian ;;
        *" fedora "*|*" rhel "*|*" centos "*)                echo fedora ;;
        *" arch "*|*" manjaro "*|*" endeavouros "*)          echo arch ;;
        *" suse "*|*" opensuse"*|*" sles "*)                 echo suse ;;   # opensuse-leap / -tumbleweed carry the prefix
        *) echo unknown ;;
    esac
}

# Package name for a command, per distro family (only where it differs from the
# command name).
bx_pkg_for() {
    local cmd="$1" fam="$2"
    case "$cmd" in
        borg)       [ "$fam" = arch ] && echo borg || echo borgbackup ;;
        btrfs)      echo btrfs-progs ;;
        mkfs.btrfs) echo btrfs-progs ;;
        bootctl|systemd-inhibit|udevadm) echo systemd ;;
        findmnt|lsblk|blkid|wipefs|sfdisk|mountpoint) echo util-linux ;;
        awk)        echo gawk ;;
        timeshift)  echo timeshift ;;
        snapper)    echo snapper ;;
        mount.ecryptfs) echo ecryptfs-utils ;;
        backintime) case "$fam" in
                        debian) echo "backintime-common backintime-qt" ;;
                        fedora|suse) echo backintime-qt ;;
                        *) echo backintime ;;   # arch: AUR only — the install fails loudly, deploy.sh says how
                    esac ;;
        *)          echo "$cmd" ;;   # rsync, cryptsetup, dracut, etc. match their package name
    esac
}

# The non-interactive install command for this host's package manager ("" if unknown).
bx_pkg_install_cmd() {
    case "$(bx_distro_family)" in
        debian) echo "apt-get update -qq && apt-get install -y" ;;
        fedora) echo "dnf install -y" ;;
        arch)   echo "pacman -S --noconfirm --needed" ;;
        suse)   echo "zypper --non-interactive install" ;;
        *)      echo "" ;;
    esac
}

# bx_ensure_deps cmd...  — check each command; install any that are missing.
# Set BX_DEP_DRYRUN=1 to report and show the install command without running it.
# Returns 0 when everything is present (or was installed), 1 otherwise.
bx_ensure_deps() {
    local cmd missing=() pkgs=() fam ic still=()
    for cmd in "$@"; do command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd"); done
    if [ ${#missing[@]} -eq 0 ]; then echo "[deps] all present: $*"; return 0; fi
    fam=$(bx_distro_family)
    echo "[deps] MISSING: ${missing[*]}   (distro family: $fam)"
    if [ "$(id -u)" -ne 0 ]; then
        echo "[deps] not running as root — cannot install. Install manually: ${missing[*]}"
        return 1
    fi
    ic=$(bx_pkg_install_cmd)
    if [ -z "$ic" ]; then
        echo "[deps] unknown package manager — install manually: ${missing[*]}"
        return 1
    fi
    for cmd in "${missing[@]}"; do pkgs+=("$(bx_pkg_for "$cmd" "$fam")"); done
    mapfile -t pkgs < <(printf '%s\n' "${pkgs[@]}" | sort -u)
    if [ "${BX_DEP_DRYRUN:-0}" = 1 ]; then
        echo "[deps] (dry-run) would install: ${pkgs[*]}   via: $ic"
        return 0
    fi
    echo "[deps] installing: ${pkgs[*]}   via: $ic"
    # shellcheck disable=SC2086
    if ! eval "$ic ${pkgs[*]}"; then
        echo "[deps] ERROR: package install failed for: ${pkgs[*]}"
        return 1
    fi
    for cmd in "${missing[@]}"; do command -v "$cmd" >/dev/null 2>&1 || still+=("$cmd"); done
    if [ ${#still[@]} -ne 0 ]; then
        echo "[deps] ERROR: still missing after install: ${still[*]}"
        return 1
    fi
    echo "[deps] installed OK: ${pkgs[*]}"
    return 0
}
