#!/usr/bin/env bash
#
# linux-backup-system — restore-verified multi-layer Linux backups for every distro and boot layout
# https://github.com/doug445/linux-backup-system
#
# Copyright (c) 2026 William MacKinnon <spilled-bowline0j@icloud.com>
# SPDX-License-Identifier: MIT
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# backup-common.sh — shared library for the linux-backup-system fleet tooling.
#
# Sourced by borg-backup.sh, backintime-backup.sh, the Timeshift wrapper, the
# restore scripts and the drive-attach unit. Everything host-specific lives in
# /etc/backup-system.conf (generated by deploy.sh); every path that depends on
# the machine's disk or boot layout is DERIVED AT RUN TIME here, never hardcoded,
# so one copy of every script runs unchanged on every distro and every boot
# layout (systemd-boot/GRUB, UKI/standard, encrypted or plain /boot).
#
# This file only defines variables and functions; it starts nothing.

# Version of the suite. Printed in every detection dump and by backup-diag.sh so
# a report can be tied to a release; bump with each tag.
# shellcheck disable=SC2034  # read by every script that sources this file
# Sourced from zsh, dash or ksh: this library is bash (arrays, [[ ]], mapfile).
[ -n "${BASH_VERSION:-}" ] || { echo "$(basename -- "${0:-lib}"): needs bash" >&2; return 1 2>/dev/null || exit 1; }
BX_VERSION="3.9.0"

# ---------------------------------------------------------------------------
# Config: load /etc/backup-system.conf, then fill any gap with a safe default.
# ---------------------------------------------------------------------------
BX_CONFIG="${BX_CONFIG:-/etc/backup-system.conf}"

# Precedence: environment > /etc/backup-system.conf > built-in default, so a
# one-off override works from the shell (KEEP=2 timeshift-backup.sh --prune-only)
# and from a unit's Environment= line, without editing the host config.
BX_CONFIG_VARS="BACKUP_MOUNT BORG_REPO BACKUP_FS_UUID BACKUP_LUKS_UUID BACKUP_KEYFILE BACKUP_MOUNT_OPTS SCHEDULE_MODE BACKUP_EXTRA_SOURCES BACKUP_EXTRA_EXCLUDES BACKUP_EXTRA_INCLUDES BACKUP_HOST_ID KEEP MIN_KEEP MIN_FREE_PCT MIN_FREE_GIB CAPACITY_HEADROOM_PCT CAPACITY_RECOMMEND_X CAPACITY_CHECK BX_LOCK_WAIT"

bx_load_config() {
    local _v _env=()
    for _v in $BX_CONFIG_VARS; do [ -n "${!_v+x}" ] && _env+=("$_v=${!_v}"); done
    # shellcheck disable=SC1090
    [ -r "$BX_CONFIG" ] && . "$BX_CONFIG"
    for _v in "${_env[@]}"; do declare -g "$_v"; done

    BACKUP_MOUNT="${BACKUP_MOUNT:-/mnt/backup}"
    BORG_REPO="${BORG_REPO:-$BACKUP_MOUNT/borg-backup}"
    BACKUP_FS_UUID="${BACKUP_FS_UUID:-}"       # empty = skip the wrong-drive guard
    BACKUP_LUKS_UUID="${BACKUP_LUKS_UUID:-}"   # for unlock-on-attach only
    BACKUP_KEYFILE="${BACKUP_KEYFILE:-}"       # for unlock-on-attach only
    BACKUP_MOUNT_OPTS="${BACKUP_MOUNT_OPTS:-}" # mount -o opts for the drive (fs-specific)
    SCHEDULE_MODE="${SCHEDULE_MODE:-adhoc}"    # adhoc | scheduled
    BACKUP_EXTRA_SOURCES="${BACKUP_EXTRA_SOURCES:-}"
    BACKUP_EXTRA_EXCLUDES="${BACKUP_EXTRA_EXCLUDES:-}"
    BACKUP_EXTRA_INCLUDES="${BACKUP_EXTRA_INCLUDES:-}"

    # The name this host's backups are filed under: borg archive prefix, the
    # Back In Time chain directory, the replica names. deploy.sh pins it in the
    # config so a later hostname change does not orphan the chain (a renamed
    # host used to start a second full copy that nothing ever pruned). Falls
    # back to the live hostname; `hostname` itself is absent on minimal Arch.
    BACKUP_HOST_ID="${BACKUP_HOST_ID:-$(hostname 2>/dev/null || uname -n 2>/dev/null)}"
    [ -n "$BACKUP_HOST_ID" ] || BACKUP_HOST_ID=$(uname -n 2>/dev/null || echo linux)

    # Retention (all layers): count-based + free-space based, never time-based.
    KEEP="${KEEP:-10}"                  # normal count to keep, any age
    MIN_KEEP="${MIN_KEEP:-3}"           # hard floor, never prune below this
    MIN_FREE_PCT="${MIN_FREE_PCT:-10}"  # keep at least this % of the drive free
    MIN_FREE_GIB="${MIN_FREE_GIB:-0}"   # and at least this many GiB free (0 = ignore)
    # Counts must be whole numbers and KEEP can never undercut the floor:
    # `head -n -0` prints EVERY line, so KEEP=0 deleted every snapshot,
    # including the one just written; KEEP=2 with MIN_KEEP=3 pruned to 2.
    local _v
    for _v in KEEP MIN_KEEP MIN_FREE_PCT MIN_FREE_GIB; do
        case "${!_v}" in ''|*[!0-9]*) echo "backup-system.conf: $_v='${!_v}' is not a whole number — using the default" >&2
            case "$_v" in KEEP) KEEP=10 ;; MIN_KEEP) MIN_KEEP=3 ;; MIN_FREE_PCT) MIN_FREE_PCT=10 ;; MIN_FREE_GIB) MIN_FREE_GIB=0 ;; esac ;;
        esac
    done
    [ "$MIN_KEEP" -ge 1 ] || MIN_KEEP=1
    if [ "$KEEP" -lt "$MIN_KEEP" ]; then
        echo "backup-system.conf: KEEP=$KEEP is below the MIN_KEEP=$MIN_KEEP floor — keeping $MIN_KEEP" >&2
        KEEP=$MIN_KEEP
    fi
    # How long a backup waits for another layer's run to finish (seconds).
    # The tray and the timers can start two layers at once; the second queues
    # rather than racing the first's free-space prune (0 = do not wait, skip).
    BX_LOCK_WAIT="${BX_LOCK_WAIT:-7200}"

    # Capacity: the drive must hold one full copy of everything in the backup
    # sources plus this much spare room, or the suite refuses to use it; and
    # it should be at least CAPACITY_RECOMMEND_X times the total size of the
    # Linux filesystems it backs up (not the whole disk).
    CAPACITY_HEADROOM_PCT="${CAPACITY_HEADROOM_PCT:-20}"
    CAPACITY_RECOMMEND_X="${CAPACITY_RECOMMEND_X:-2}"
    # refuse (default) | warn | off. The floor is measured with df on the
    # whole filesystem of each source, which on btrfs counts snapper snapshots
    # and every subvolume of that filesystem, backed up or not; a host whose
    # system disk holds 1.5 TiB of VM images beside a 100 GiB system needs
    # "warn" to use a 1 TiB drive that would hold it fine.
    CAPACITY_CHECK="${CAPACITY_CHECK:-refuse}"
}

# ---------------------------------------------------------------------------
# One lock for every layer. borg, Back In Time and Timeshift each end with a
# free-space prune; two running at once watch the drive fill from the other's
# writes and delete each other's history down to MIN_KEEP. A second Back In
# Time run also rm -rf's the first one's in-progress snapshot. The tray and
# the two Persistent= timers can start two layers within a second.
#   bx_lock            wait BX_LOCK_WAIT seconds for the lock (0 = skip)
# Returns 1 when the lock could not be taken; the caller logs and exits 0.
# ---------------------------------------------------------------------------
BX_LOCK_FILE="${BX_LOCK_FILE:-/var/lock/backup-system.lock}"
bx_lock() {
    local wait="${BX_LOCK_WAIT:-0}"
    # Called directly, never in a pipeline: the fd must open in the caller.
    exec 9>"$BX_LOCK_FILE" || return 1
    if flock -n 9; then return 0; fi
    [ "$wait" -gt 0 ] 2>/dev/null || return 1
    echo "another backup layer is running (lock $BX_LOCK_FILE) — waiting up to ${wait}s" >&2
    flock -w "$wait" 9
}

# ---------------------------------------------------------------------------
# Free space on the backup drive.
# ---------------------------------------------------------------------------
bx_free_pct() { local u; u=$(df --output=pcent "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9'); echo $(( 100 - ${u:-100} )); }
bx_free_gib() { local a; a=$(df --output=avail "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9'); echo $(( ${a:-0} / 1024 / 1024 )); }
bx_space_low() { [ "$(bx_free_pct)" -lt "$MIN_FREE_PCT" ] || [ "$(bx_free_gib)" -lt "$MIN_FREE_GIB" ]; }

# ---------------------------------------------------------------------------
# Capacity: is the backup drive big enough for this machine?
#
# Two thresholds. The FLOOR is measured against what is actually on the
# machine: the used bytes of every filesystem in the backup sources, plus
# CAPACITY_HEADROOM_PCT spare room. A drive below the floor cannot hold even
# one full copy and is refused — by deploy.sh before it formats or adopts one,
# and by every backup script before it writes. The RECOMMENDATION is measured
# against the Linux system: CAPACITY_RECOMMEND_X times the total size of the
# filesystems in the backup sources (root, /home, /boot, the ESP — each
# counted once), so the drive has room for many generations of every layer.
# Not the whole disk: on a dual-boot or Apple Silicon machine most of the disk
# belongs to another OS and is never backed up. Below that is a warning, not
# a stop.
# ---------------------------------------------------------------------------
bx_human_bytes() { # bx_human_bytes BYTES -> "1.8 TiB"
    local b="${1:-0}"
    awk -v b="$b" 'BEGIN{ split("B KiB MiB GiB TiB PiB",u," "); i=1; v=b+0;
        while (v>=1024 && i<6) { v/=1024; i++ }
        if (i==1) printf "%d %s", v, u[i]; else printf "%.1f %s", v, u[i] }'
}

# The whole disk a block device (partition, LUKS mapper, LV) ultimately sits on.
bx_disk_of() { # bx_disk_of /dev/xxx -> /dev/nvme0n1
    local d kn pk sl
    d=$(readlink -f "$1" 2>/dev/null) || return 1; kn=$(basename "$d")
    while :; do
        # device-mapper (LUKS, LVM): the parent is a sysfs slave, not PKNAME
        sl=$(ls "/sys/block/$kn/slaves" 2>/dev/null | head -1 || true)
        if [ -n "$sl" ]; then kn="$sl"; continue; fi
        # partition -> its disk
        pk=$(lsblk -dno PKNAME "/dev/$kn" 2>/dev/null | head -1 || true)
        if [ -n "$pk" ]; then kn="$pk"; continue; fi
        break
    done
    [ -b "/dev/$kn" ] && echo "/dev/$kn"
}

# Sum of one df column (used | size) across every filesystem in the backup
# sources, each counted once (btrfs subvolumes of one filesystem share one
# figure). This is the Linux portion of the machine — what a backup copies and
# what it would restore onto — not the whole disk.
_bx_sources_sum() { # _bx_sources_sum used|size
    local col="$1" m src seen=" " total=0 v
    while read -r m; do
        [ -n "$m" ] || continue
        src=$(findmnt -no SOURCE --target "$m" 2>/dev/null | sed 's/\[.*//' || true)
        [ -n "$src" ] || continue
        case "$seen" in *" $src "*) continue ;; esac
        seen="$seen$src "
        v=$(df -B1 --output="$col" "$m" 2>/dev/null | tail -1 | tr -dc '0-9')
        total=$(( total + ${v:-0} ))
    done < <(bx_backup_sources)
    echo "$total"
}
bx_sources_used_bytes()  { _bx_sources_sum used; }
bx_sources_total_bytes() { _bx_sources_sum size; }

# Size in bytes of the disk the root filesystem lives on (0 if unresolvable).
# Informational — the capacity policy deliberately does NOT use it.
bx_system_disk_bytes() {
    local src disk
    src=$(findmnt -no SOURCE --target / 2>/dev/null | sed 's/\[.*//' || true)
    disk=$(bx_disk_of "${src:-/dev/null}" 2>/dev/null || true)
    [ -n "$disk" ] && lsblk -dnbo SIZE "$disk" 2>/dev/null | head -1 || echo 0
}

# bx_capacity_verdict DRIVE_BYTES USED_BYTES LINUX_TOTAL_BYTES
#   -> "refuse|warn|ok FLOOR RECOMMENDED"  (pure arithmetic; fixture-tested)
bx_capacity_verdict() {
    local drive="${1:-0}" used="${2:-0}" linux="${3:-0}" floor rec v
    floor=$(( used + used * ${CAPACITY_HEADROOM_PCT:-20} / 100 ))
    rec=$(( linux * ${CAPACITY_RECOMMEND_X:-2} ))
    if   [ "$drive" -lt "$floor" ]; then v=refuse
    elif [ "$linux" -gt 0 ] && [ "$drive" -lt "$rec" ]; then v=warn
    else v=ok; fi
    echo "$v $floor $rec"
}

# bx_check_backup_capacity [DRIVE_BYTES] — one line of verdict for the drive
# mounted at BACKUP_MOUNT (or a candidate disk's size in bytes). Returns 1 on
# refuse, 0 otherwise; the line explains either way.
bx_check_backup_capacity() {
    local drive="${1:-}" used linux v floor rec
    if [ "${CAPACITY_CHECK:-refuse}" = off ]; then echo "capacity: check disabled (CAPACITY_CHECK=off)"; return 0; fi
    if [ -z "$drive" ]; then
        drive=$(df -B1 --output=size "$BACKUP_MOUNT" 2>/dev/null | tail -1 | tr -dc '0-9')
        [ -n "$drive" ] || { echo "capacity: $BACKUP_MOUNT is not mounted — cannot size it"; return 1; }
    fi
    used=$(bx_sources_used_bytes); linux=$(bx_sources_total_bytes)
    read -r v floor rec < <(bx_capacity_verdict "$drive" "$used" "$linux")
    case "$v" in
        refuse) if [ "${CAPACITY_CHECK:-refuse}" = warn ]; then
                    echo "capacity: WARNING (CAPACITY_CHECK=warn) — drive holds $(bx_human_bytes "$drive"), a full backup of $(bx_human_bytes "$used") plus ${CAPACITY_HEADROOM_PCT}% spare needs $(bx_human_bytes "$floor"); continuing"; return 0
                fi
                echo "capacity: REFUSED — drive holds $(bx_human_bytes "$drive"), but a full backup of $(bx_human_bytes "$used") plus ${CAPACITY_HEADROOM_PCT}% spare needs $(bx_human_bytes "$floor")$([ "$linux" -gt 0 ] && echo "; recommended: ${CAPACITY_RECOMMEND_X}x the $(bx_human_bytes "$linux") of Linux filesystems = $(bx_human_bytes "$rec")") — CAPACITY_CHECK=warn in the config overrides"; return 1 ;;
        warn)   echo "capacity: OK but small — drive $(bx_human_bytes "$drive") holds the $(bx_human_bytes "$used") of data (floor $(bx_human_bytes "$floor")); recommended ${CAPACITY_RECOMMEND_X}x the $(bx_human_bytes "$linux") of Linux filesystems = $(bx_human_bytes "$rec")" ;;
        *)      echo "capacity: OK — drive $(bx_human_bytes "$drive") for $(bx_human_bytes "$used") of data (floor $(bx_human_bytes "$floor")$([ "$linux" -gt 0 ] && echo ", recommended $(bx_human_bytes "$rec") = ${CAPACITY_RECOMMEND_X}x the Linux filesystems"))" ;;
    esac
    return 0
}

# ---------------------------------------------------------------------------
# Filesystem / layout detection.
# ---------------------------------------------------------------------------
bx_root_fstype() { findmnt -no FSTYPE / 2>/dev/null; }
bx_is_btrfs()    { [ "$(bx_root_fstype)" = btrfs ]; }

# The local-snapshot / replica layer this host should use:
#   btrfs -> "btrfs" (send/receive replicas, handled in borg-backup.sh)
#   else  -> "timeshift" (rsync snapshots) if timeshift is installed, else "none"
bx_snapshot_engine() {
    if bx_is_btrfs; then echo btrfs
    elif command -v timeshift >/dev/null 2>&1; then echo timeshift
    else echo none; fi
}

# Absolute source paths to feed a file-level backup (borg / BIT): "/" plus
# EVERY separately mounted local filesystem the machine is made of — not a
# whitelist. openSUSE mounts /var, /opt, /srv, /root, /usr/local and the GRUB
# module dirs as their own subvolumes; older installs put /var, /usr or /opt
# on their own partitions; a ZFS root is twenty datasets. Each has its own
# st_dev, so borg --one-file-system archived them as empty directories and the
# btrfs replicas never included them. Anything not local — the backup drive,
# removable media, network shares, snap/flatpak images, runtime mounts — is
# left out, as are bind mounts of a directory already inside a listed source.
# Extra paths can be added via BACKUP_EXTRA_SOURCES in the config.
#
# BX_MOUNT_TABLE: a file of `TARGET FSTYPE SOURCE OPTIONS` lines in
# `findmnt -rno` form stands in for the live mount table (fixture tests).
_bx_mount_table() {
    if [ -n "${BX_MOUNT_TABLE:-}" ]; then cat "$BX_MOUNT_TABLE"; else findmnt -rno TARGET,FSTYPE,SOURCE,OPTIONS 2>/dev/null; fi
}
bx_backup_sources() {
    local t f src opts dev sub subvol seen=" " m bm="${BACKUP_MOUNT:-/mnt/backup}"
    {
        echo /
        # ${...:-}: deploy.sh runs under set -u without bx_load_config.
        while read -r t f src opts; do
            [ -n "$t" ] && [ "$t" != / ] || continue
            case "$f" in
                ext2|ext3|ext4|xfs|btrfs|f2fs|zfs|bcachefs|jfs|nilfs2|reiserfs|vfat|exfat|ntfs|ntfs3) ;;
                *) continue ;;   # tmpfs, overlay, squashfs, nfs/cifs/fuse, proc/sys — not this machine's disk
            esac
            case "$t" in
                "$bm"|"$bm"/*|/run/*|/mnt|/mnt/*|/media|/media/*|/tmp|/tmp/*|/var/tmp|/var/tmp/*|/snap/*|/var/lib/snapd/snap/*|/proc/*|/sys/*|/dev/*) continue ;;
                */.snapshots|*/.snapshots/*) continue ;;   # snapper's own subvolume, never a source
            esac
            # Bind mount of a directory: SOURCE carries the directory in
            # brackets (/dev/x[/@/srv/data]) that is not the mounted subvolume
            # (subvol=/@). Its files are already inside the parent source.
            dev=${src%%\[*}; sub=""; case "$src" in *"["*) sub=${src#*\[}; sub=${sub%]} ;; esac
            subvol=""; case ",$opts," in *,subvol=*) subvol=${opts#*subvol=}; subvol=${subvol%%,*} ;; esac
            if [ -n "$sub" ] && [ "$f" != btrfs ]; then continue; fi                 # ext4 bind of a subdir
            if [ "$f" = btrfs ] && [ -n "$sub" ] && [ -n "$subvol" ] && [ "$sub" != "$subvol" ]; then continue; fi
            # Same filesystem (same device + same subvolume) mounted twice: once.
            case "$seen" in *" ${dev}[${sub}] "*) continue ;; esac
            seen="$seen${dev}[${sub}] "
            printf '%s\n' "$t"
        done < <(_bx_mount_table)
        local _xs=(); read -ra _xs <<<"${BACKUP_EXTRA_SOURCES:-}"   # no glob expansion
        for m in "${_xs[@]}"; do
            [ "$m" = / ] && continue
            if [ -n "${BX_MOUNT_TABLE:-}" ]; then grep -qE "^$m " "$BX_MOUNT_TABLE" && printf '%s\n' "$m"
            else mountpoint -q "$m" 2>/dev/null && printf '%s\n' "$m"; fi
        done
    } | awk '!seen[$0]++' | { read -r first; echo "$first"; sort -u; }
}

# The universal exclude list for a file-level backup (borg and Back In Time
# read the same one, so the two layers agree on what "everything" is), one
# anchored path pattern per line. Runtime and cache trees, trash, package and
# language caches, snapper's snapshot dirs, the local snapshot staging dir,
# flatpak's image store, and every ACTIVE SWAPFILE (8–16 GiB of churn that
# also makes `btrfs subvolume snapshot` of the root refuse). Nothing personal:
# per-host additions go in BACKUP_EXTRA_EXCLUDES.
bx_excludes() {
    printf '%s\n' '/dev/*' '/proc/*' '/sys/*' '/tmp/*' '/run/*' '/mnt/*' '/media/*' \
        '/var/tmp/*' '/var/cache/*' '/var/log/journal/*' '/snap/*' '/var/lib/snapd/snap/*' \
        '/home/*/.cache/*' '/home/*/.local/share/Trash/*' '/home/*/.npm/_cacache/*' \
        '/home/*/.cargo/registry/*' '/root/.cache/*' '/root/.local/share/Trash/*' \
        '/var/lib/flatpak/*' '/.snapshots/*' '/home/.snapshots/*' '/.backup-snapshots/*'
    local f type _
    { read -r _; while read -r f type _; do [ "$type" = file ] && printf '%s\n' "$f"; done; } < /proc/swaps 2>/dev/null
    [ -n "${BACKUP_MOUNT:-}" ] && printf '%s\n' "${BACKUP_MOUNT}/*"
    # read -a, not an unquoted for-in: the patterns carry globs, and
    # `for e in ${BACKUP_EXTRA_EXCLUDES}` expanded "/home/*" into the files in
    # /home before borg ever saw the pattern.
    local e ex=()
    read -ra ex <<<"${BACKUP_EXTRA_EXCLUDES:-}"
    for e in "${ex[@]}"; do printf '%s\n' "$e"; done
    return 0
}

# Is a source's WHOLE tree on the exclude list ("<mount>/*")? Such a mount is
# still listed as a source (borg records the empty mount point) but must not
# get a btrfs replica: send/receive ignores excludes, and Manjaro's @cache
# subvolume sent 54 GiB of package cache to the drive on every run.
# bx_includes — BACKUP_EXTRA_INCLUDES, one anchored pattern per line: paths
# re-included INSIDE an excluded tree. They go before every exclude (borg and
# rsync both take the first matching rule), so BACKUP_EXTRA_EXCLUDES="/home/*/*"
# with BACKUP_EXTRA_INCLUDES="/home/*/.config /home/*/.ssh" keeps a user's
# configuration and keys and drops their data. A directory pattern carries its
# whole subtree. No glob expansion (read -a).
bx_includes() {
    local i inc=()
    read -ra inc <<<"${BACKUP_EXTRA_INCLUDES:-}"
    for i in "${inc[@]}"; do printf '%s\n' "${i%/}"; done
    return 0
}

# bx_borg_patterns SOURCE... — borg --pattern arguments, one per line, in the
# order borg must see them: sources under a blanket-excluded tree first
# (BACKUP_EXTRA_SOURCES=/mnt/data), then BACKUP_EXTRA_INCLUDES, then every
# exclude. The one place this order is decided: borg-backup.sh and the restore
# test bed build the same archive from it.
bx_borg_patterns() {
    local s i e
    for s in "$@"; do
        case "$s" in /mnt/*|/media/*|/run/*|/tmp/*) printf -- '--pattern=+%s\n' "$s" ;; esac
    done
    while IFS= read -r i; do [ -n "$i" ] && printf -- '--pattern=+%s\n' "$i"; done < <(bx_includes)
    while IFS= read -r e; do [ -n "$e" ] && printf -- '--pattern=-%s\n' "$e"; done < <(bx_excludes)
    return 0
}

bx_source_fully_excluded() { # bx_source_fully_excluded MOUNT
    # Not `bx_excludes | grep -q`: grep -q exits at the first match, the
    # writer gets SIGPIPE, and under the callers' `set -o pipefail` a found
    # match came back as "not excluded" whenever the list was long.
    local ex; ex=$(bx_excludes)
    grep -qxF -- "${1%/}/*" <<<"$ex"
}

# ---------------------------------------------------------------------------
# btrfs replicas, sent INCREMENTALLY. A send without a parent writes a full
# copy of the subvolume every run, sharing nothing with the replica before it:
# a 1.8 TiB drive held two generations of a 600 GiB system, never the KEEP=10
# the retention promises. The newest local read-only snapshot of a label is
# kept after a good send as the next run's parent (-p); the receive side
# needs that same snapshot's replica, complete, on the drive. Missing either
# one — a new drive, a pruned replica, a first run — means a full send, said
# so in the log.
#
# bx_replica_parent LABEL LOCAL_DIR DEST_DIR — the snapshot name (basename)
# usable as the parent, or nothing. The newest local snapshot of the label
# whose replica exists on the drive, read-only and received.
bx_replica_parent() {
    local label="$1" ldir="$2" ddir="$3" p n
    while IFS= read -r p; do
        [ -d "$p" ] || continue
        n=$(basename "$p")
        [ -d "$ddir/$n" ] || continue
        [ "$(btrfs property get "$ddir/$n" ro 2>/dev/null | sed -n 's/^ro=//p')" = true ] || continue
        btrfs subvolume show "$ddir/$n" 2>/dev/null | grep -qE 'Received UUID:[[:space:]]+[0-9a-f]{8}-' || continue
        printf '%s\n' "$n"
        return 0
    done < <(ls -1d "$ldir/${label}_"[0-9]* 2>/dev/null | sort -r)
    return 0
}

# bx_replica_send LABEL SRC LOCAL_DIR DEST_DIR STAMP [LOGFILE]
#   Snapshot SRC read-only as LOCAL_DIR/LABEL_STAMP, send it to DEST_DIR
#   (incremental from bx_replica_parent when there is one), and verify the
#   replica is read-only. On success the new local snapshot is the only one
#   of its label left (the next parent) and one line says "incremental from
#   <parent>" or "full"; returns 0. On failure the half-written replica and
#   the new local snapshot are removed and the previous parent is kept, so
#   the next run is still incremental; one line says why; returns 1.
#   Never pipe btrfs send/receive through tee: the three-way pipe made
#   receive fail with SIGPIPE.
bx_replica_send() {
    local label="$1" src="$2" ldir="$3" ddir="$4" stamp="$5" logf="${6:-/dev/null}"
    local name="${label}_$stamp" parent ro d pargs=() rc=()
    parent=$(bx_replica_parent "$label" "$ldir" "$ddir")
    [ -n "$parent" ] && pargs=(-p "$ldir/$parent")
    if ! btrfs subvolume snapshot -r "$src" "$ldir/$name" >>"$logf" 2>&1; then
        echo "could not snapshot $src$(awk 'NR>1 && $2=="file"{f=1} END{if(f) print " (an ACTIVE SWAPFILE on a subvolume makes the kernel refuse to snapshot it)"}' /proc/swaps 2>/dev/null)"
        return 1
    fi
    btrfs send "${pargs[@]}" "$ldir/$name" 2>>"$logf" | btrfs receive "$ddir/" >>"$logf" 2>&1
    rc=("${PIPESTATUS[@]}")
    # sed, not grep -P: a grep without PCRE (busybox, --disable-perl-regexp)
    # returned "" and every replica just written was deleted as incomplete.
    ro=$(btrfs property get "$ddir/$name" ro 2>/dev/null | sed -n 's/^ro=//p')
    if [ "${rc[0]}" = 0 ] && [ "${rc[1]}" = 0 ] && [ "$ro" = true ]; then
        for d in "$ldir/${label}_"[0-9]*; do
            [ -d "$d" ] && [ "$d" != "$ldir/$name" ] && btrfs subvolume delete "$d" >>"$logf" 2>&1
        done
        if [ -n "$parent" ]; then echo "incremental from $parent"; else echo "full"; fi
        return 0
    fi
    echo "send rc=${rc[0]:-?} receive rc=${rc[1]:-?} ro=${ro:-missing}${parent:+ (incremental from $parent)}"
    [ -d "$ddir/$name" ] && btrfs subvolume delete "$ddir/$name" >>"$logf" 2>&1
    btrfs subvolume delete "$ldir/$name" >>"$logf" 2>&1
    return 1
}

# The boot-firmware partition for this host — the ESP on UEFI machines, the
# vfat firmware partition on a Raspberry Pi — from live mounts then fstab, so a
# declared-but-unmounted one is still found. Empty on legacy BIOS. These are
# the ONLY paths the suite recognises; a new layout is added here and in the
# matching lists in backup-verify.sh and restore-rebuild-boot.sh.
BX_ESP_PATHS='/efi|/boot/efi|/boot/firmware'
bx_esp_mount() {
    local m
    m=$({ findmnt -rno TARGET,FSTYPE 2>/dev/null | awk '$2=="vfat"{print $1}'
          awk '$1 !~ /^#/ && $3=="vfat"{print $2}' /etc/fstab 2>/dev/null
        } | grep -xE "$BX_ESP_PATHS" | head -1)
    # No ESP at a dedicated path: /boot itself may be the ESP (systemd-boot on
    # Arch mounts it there). Only when /boot is vfat and is not an XBOOTLDR.
    [ -z "$m" ] && bx_boot_is_esp && m=/boot
    [ -n "$m" ] && echo "$m"
}

# bx_parttype_kind PARTTYPE — classify a partition type as the boot firmware
# and systemd-boot see it: esp (GPT EFI System, or MBR type 0xef), xbootldr
# (GPT Linux extended boot), other. Case-insensitive; pure (fixture-tested).
bx_parttype_kind() {
    case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
        c12a7328-f81f-11d2-ba4b-00a0c93ec93b|0xef) echo esp ;;
        bc13c2ff-59e6-4262-a352-b275fd6f7172|0xea) echo xbootldr ;;
        *) echo other ;;
    esac
}

# bx_dev_parttype_kind DEV — the same, for a block device (lsblk PARTTYPE).
# "unknown" when the type cannot be read (not a partition, lsblk too old).
bx_dev_parttype_kind() {
    local pt; pt=$(lsblk -dno PARTTYPE "$1" 2>/dev/null | head -1 | tr -d ' ' || true)
    [ -n "$pt" ] && bx_parttype_kind "$pt" || echo unknown
}

# Is /boot the ESP itself (no separate /efi or /boot/efi)? Yes when /boot is a
# vfat mount whose partition is typed EFI System — or, where the type cannot be
# read, when it holds an EFI/ directory and no separate ESP is mounted. An
# XBOOTLDR /boot (vfat too, next to an ESP at /efi) is never the ESP.
bx_boot_is_esp() {
    local src kind
    [ "$(findmnt -no FSTYPE /boot 2>/dev/null)" = vfat ] || return 1
    src=$(findmnt -no SOURCE /boot 2>/dev/null)
    kind=$(bx_dev_parttype_kind "$src")
    case "$kind" in
        esp) return 0 ;;
        unknown) [ -d /boot/EFI ] && ! mountpoint -q /efi 2>/dev/null && ! mountpoint -q /boot/efi 2>/dev/null ;;
        *) return 1 ;;
    esac
}

# Raspberry Pi firmware boot: no UEFI, no GRUB, no systemd-boot. The SoC's
# firmware reads config.txt / cmdline.txt / kernel*.img from a vfat partition
# (/boot/firmware on Raspberry Pi OS bookworm+, /boot before). Recognised by
# config.txt in that partition on a machine without EFI. UNTESTED ON METAL.
bx_pi_firmware_boot() {
    [ -d /sys/firmware/efi ] && return 1
    [ -f "${BX_PI_FW:-/boot/firmware}/config.txt" ] || [ -f /boot/config.txt ]
}

# Classify an archive/snapshot listing (paths relative to the root, one per
# line) by what would let it boot. Prints: uki kern gcfg sdb pifw oth — counts
# of UKIs, plain kernels, grub.cfg files, systemd-boot entries, Raspberry Pi
# firmware config files, and other bootloader configs (Limine, rEFInd,
# syslinux/extlinux) — without the last, a CachyOS/Limine archive failed verify
# with "no bootloader config". Plain kernels include the kernel-install Type #1
# layout, <esp>/<machine-id>/<version>/linux, which systemd-boot without UKIs
# uses on Fedora, Debian and Arch when the ESP is /efi or XBOOTLDR is /boot. Only boot/ and efi/ are considered: /usr/lib/modules
# keeps a vmlinuz copy on Fedora and would satisfy a root-only archive.
# The path segment between boot/|efi/ and the file is optional: with the ESP
# at /efi a UKI lists as efi/EFI/Linux/x.efi and an entry as
# efi/loader/entries/x.conf, with nothing in between — the old patterns
# required a directory there and missed every systemd-boot host with /efi.
bx_boot_listing_counts() { # bx_boot_listing_counts LISTING_FILE
    local f="$1"
    printf '%s %s %s %s %s %s\n' \
        "$(grep -icE '^(boot|efi)/(.*/)?EFI/Linux/.*\.efi$' "$f")" \
        "$(grep -cE '^(boot|efi)/(.*/)?(vmlinuz|vmlinux|Image|kernel)(-|$)|^(boot|efi)/[0-9a-f]{32}/[^/]+/linux$|^boot/(firmware/)?kernel[0-9_a-z]*\.img$' "$f")" \
        "$(grep -icE '^(boot|efi)/(.*/)?grub\.cfg$' "$f")" \
        "$(grep -icE '^(boot|efi)/(.*/)?loader/(loader\.conf|entries/.+\.conf)$' "$f")" \
        "$(grep -cE '^boot/(firmware/)?(config|cmdline)\.txt$' "$f")" \
        "$(grep -icE '^(boot|efi)/(.*/)?(limine\.conf|refind\.conf|extlinux\.conf|syslinux\.cfg)$' "$f")"
}

# Kernels in a listing that have no initramfs beside them, one path per line.
# A plain kernel cannot mount a LUKS, LVM or btrfs-subvolume root without one;
# dracut running out of memory on the last update leaves vmlinuz-X without
# initramfs-X.img, and "the archive has a kernel" passed. Pairs by the
# version suffix in every naming scheme this suite meets: Debian
# vmlinuz-V + initrd.img-V, Fedora/Asahi vmlinuz-V + initramfs-V.img, Arch
# vmlinuz-linux + initramfs-linux.img, openSUSE vmlinuz-V + initrd-V, Alpine
# vmlinuz-lts + initramfs-lts, kernel-install <id>/<ver>/linux + initrd.
bx_kernels_without_initrd() { # bx_kernels_without_initrd LISTING_FILE
    local f="$1" k dir base v
    grep -E '^(boot|efi)/(.*/)?(vmlinuz|vmlinux|Image|kernel)-[^/]+$|^(boot|efi)/[0-9a-f]{32}/[^/]+/linux$' "$f" 2>/dev/null \
    | while IFS= read -r k; do
        dir=${k%/*}; base=${k##*/}
        if [ "$base" = linux ]; then
            grep -qxF "$dir/initrd" "$f" || printf '%s\n' "$k"
            continue
        fi
        v=${base#*-}
        grep -qxF -e "$dir/initramfs-$v.img" -e "$dir/initrd.img-$v" -e "$dir/initrd-$v" -e "$dir/initramfs-$v" "$f" \
            || printf '%s\n' "$k"
    done
    return 0
}

# Is /boot its own filesystem (vs a directory on root)?
bx_boot_is_mount() { mountpoint -q /boot 2>/dev/null; }

# ---------------------------------------------------------------------------
# Is the configured drive physically here? A yanked LUKS drive leaves its
# mapper node, the filesystem UUID link inside it, and the mount all in place;
# only the LUKS partition's own by-uuid link (or, on a plain drive, the
# filesystem's) disappears. Test that, never the mapper or the mount.
# ---------------------------------------------------------------------------
bx_backup_drive_present() {
    if [ -n "${BACKUP_LUKS_UUID:-}" ]; then [ -e "/dev/disk/by-uuid/$BACKUP_LUKS_UUID" ]
    elif [ -n "${BACKUP_FS_UUID:-}" ]; then [ -e "/dev/disk/by-uuid/$BACKUP_FS_UUID" ]
    else return 1; fi
}

# Does a block device still rest on real hardware? A device-mapper node (LUKS,
# LVM) outlives a yanked disk; what disappears is its sysfs slave link. Walk
# the slave chain down to a non-dm device and require one to exist. Reads
# sysfs only, so it works unprivileged.
bx_dev_is_live() { # bx_dev_is_live /dev/xxx
    local dev="$1" node kn s
    case "$dev" in /*) ;; *) return 0 ;; esac   # nas:/export, //srv/share — not a block device, nothing to yank
    [ -e "$dev" ] || return 1
    node=$(readlink -f "$dev" 2>/dev/null || true); kn=$(basename "${node:-$dev}")
    # Every whole disk has a slaves/ directory too — EMPTY. Only a non-empty
    # one marks a stacked device; treating the empty one as "dm device with
    # no live slave" declared every filesystem or LUKS container that sits
    # directly on a whole disk (cryptsetup luksFormat /dev/sdb, the common
    # external-drive form) dead, and every backup script refused to run.
    if [ -d "/sys/block/$kn/slaves" ] && [ -n "$(ls -A "/sys/block/$kn/slaves" 2>/dev/null)" ]; then
        for s in "/sys/block/$kn/slaves"/*; do
            [ -e "$s" ] || continue
            bx_dev_is_live "/dev/$(basename "$s")" && return 0
        done
        return 1     # a dm device with no live slave: its disk is gone
    fi
    [ -b "$node" ] && { [ -d "/sys/class/block/$kn" ] || [ -d "/sys/block/$kn" ]; }
}

# Is MOUNT a mount whose backing block device still exists? A dead mount (drive
# unplugged) still answers `mountpoint -q` yes; this does not.
bx_mount_is_live() { # bx_mount_is_live MOUNT
    local m="$1" src fst
    mountpoint -q "$m" 2>/dev/null || return 1
    fst=$(findmnt -no FSTYPE --target "$m" 2>/dev/null || true)
    case "$fst" in nfs|nfs4|cifs|smb3|fuse.sshfs|fuse.*|9p|virtiofs|ceph|glusterfs) return 0 ;; esac  # a NAS cannot be unplugged
    src=$(findmnt -no SOURCE --target "$m" 2>/dev/null | sed 's/\[.*//' || true)
    [ -n "$src" ] || return 1
    bx_dev_is_live "$src"
}

# ---------------------------------------------------------------------------
# Wrong-drive guard: refuse to write to a drive whose fs UUID is not the one the
# config pins, or whose backing device is gone (a yanked drive leaves a mount
# that looks mounted and swallows writes). A no-op on the UUID when
# BACKUP_FS_UUID is empty (unconfigured). Returns non-zero with the reason.
# ---------------------------------------------------------------------------
bx_check_backup_drive() {
    mountpoint -q "$BACKUP_MOUNT" 2>/dev/null || { echo "backup mount $BACKUP_MOUNT is not mounted"; return 1; }
    bx_mount_is_live "$BACKUP_MOUNT" || { echo "backup mount $BACKUP_MOUNT is dead: its device is gone (drive unplugged?) — run borg-backup-drive-detach.sh"; return 1; }
    [ -n "$BACKUP_FS_UUID" ] || return 0
    local actual; actual=$(findmnt -n -o UUID --target "$BACKUP_MOUNT" 2>/dev/null)
    if [ "$actual" != "$BACKUP_FS_UUID" ]; then
        echo "wrong drive at $BACKUP_MOUNT: expected fs UUID $BACKUP_FS_UUID, found ${actual:-<none>}"
        return 1
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Why did the drive go away? Two causes look identical from a backup script —
# "not mounted", "repository does not exist" — and neither is dead hardware:
#   1. a USB-SATA/NVMe bridge (Realtek RTL9201/9210, some JMicron/ASMedia)
#      resets its UAS link under a long sustained write; the drive drops for a
#      second and re-enumerates;
#   2. USB authorization then keeps it out. USBGuard with a lock hook
#      (InsertedDevicePolicy=block while the session is locked) blocks every
#      re-plugged device — the backup drive, and the mouse receiver the user
#      moves to "test the port" — until the session is unlocked. It looks like
#      every USB port died; unlocking, not rebooting, brings them back.
# Read-only; sysfs and (as root) the kernel log. BX_SYSFS_USB: fixture root.
# ---------------------------------------------------------------------------
# bx_usb_blocked_devices — "port vid:pid product" for every USB device the
# kernel holds unauthorized (authorized=0), one per line.
bx_usb_blocked_devices() {
    local d base="${BX_SYSFS_USB:-/sys/bus/usb/devices}"
    for d in "$base"/*; do
        [ -f "$d/authorized" ] && [ -f "$d/idVendor" ] || continue
        [ "$(cat "$d/authorized" 2>/dev/null)" = 0 ] || continue
        printf '%s %s:%s %s\n' "$(basename "$d")" "$(cat "$d/idVendor")" "$(cat "$d/idProduct" 2>/dev/null)" "$(cat "$d/product" 2>/dev/null || echo '?')"
    done
    return 0
}

# bx_drive_gone_hint — explanation lines when the drive is missing; nothing
# when there is nothing to say.
bx_drive_gone_hint() {
    local blocked resets
    blocked=$(bx_usb_blocked_devices)
    if [ -n "$blocked" ]; then
        echo "USB devices present but NOT AUTHORIZED (the drive may be one of them): $(tr '\n' ';' <<<"$blocked" | sed 's/;$//; s/;/; /g')"
        if command -v usbguard >/dev/null 2>&1; then
            echo "USBGuard is installed: a device re-plugged (or re-enumerated after a bridge reset) while the session is locked stays blocked — unlock the session, or: usbguard list-devices | grep block ; usbguard allow-device <id>"
        fi
    fi
    if [ "$(id -u)" -eq 0 ] && command -v journalctl >/dev/null 2>&1; then
        resets=$(journalctl -k -b --since "-6h" --no-pager -o cat 2>/dev/null | grep -cE 'uas_zap_pending|USB disconnect.*|reset (Super|high)Speed USB device' || true)
        [ "${resets:-0}" -gt 0 ] && echo "kernel log: $resets USB disconnect/reset line(s) in the last 6 h — if the bridge resets under sustained writes, see README 'The drive dropped in the middle of a backup'"
    fi
    return 0
}

# ---------------------------------------------------------------------------
# Dependencies: identify missing commands up front and install them, rather
# than letting a tool fail silently mid-run. Distro-family aware.
# ---------------------------------------------------------------------------
bx_distro_family() {
    local ID="" ID_LIKE=""
    # BX_OS_RELEASE lets the fixture test feed synthetic os-release files.
    # shellcheck disable=SC1090,SC1091
    [ -r "${BX_OS_RELEASE:-/etc/os-release}" ] && . "${BX_OS_RELEASE:-/etc/os-release}"
    case " ${ID:-} ${ID_LIKE:-} " in
        *" debian "*|*" ubuntu "*|*" linuxmint "*|*" pop "*) echo debian ;;
        *" fedora "*|*" rhel "*|*" centos "*)                echo fedora ;;
        *" arch "*|*" manjaro "*|*" endeavouros "*)          echo arch ;;
        *" suse "*|*" opensuse"*|*" sles "*)                 echo suse ;;   # opensuse-leap / -tumbleweed carry the prefix
        *) echo unknown ;;
    esac
}

# Package name for a command, per distro family (only where it differs from the
# command name).
bx_pkg_for() {
    local cmd="$1" fam="$2"
    case "$cmd" in
        borg)       [ "$fam" = arch ] && echo borg || echo borgbackup ;;
        btrfs)      echo btrfs-progs ;;
        mkfs.btrfs) echo btrfs-progs ;;
        bootctl|systemd-inhibit|udevadm) echo systemd ;;
        findmnt|lsblk|blkid|wipefs|sfdisk|mountpoint) echo util-linux ;;
        awk)        echo gawk ;;
        timeshift)  echo timeshift ;;
        snapper)    echo snapper ;;
        mount.ecryptfs) echo ecryptfs-utils ;;
        backintime) case "$fam" in
                        debian) echo "backintime-common backintime-qt" ;;
                        fedora|suse) echo backintime-qt ;;
                        *) echo backintime ;;   # arch: AUR only — the install fails loudly, deploy.sh says how
                    esac ;;
        *)          echo "$cmd" ;;   # rsync, cryptsetup, dracut, etc. match their package name
    esac
}

# The non-interactive install command for this host's package manager ("" if unknown).
bx_pkg_install_cmd() {
    case "$(bx_distro_family)" in
        debian) echo "apt-get update -qq && apt-get install -y" ;;
        fedora) echo "dnf install -y" ;;
        arch)   echo "pacman -S --noconfirm --needed" ;;
        suse)   echo "zypper --non-interactive install" ;;
        *)      echo "" ;;
    esac
}

# bx_ensure_deps cmd...  — check each command; install any that are missing.
# Set BX_DEP_DRYRUN=1 to report and show the install command without running it.
# Returns 0 when everything is present (or was installed), 1 otherwise.
bx_ensure_deps() {
    local cmd missing=() pkgs=() fam ic still=()
    for cmd in "$@"; do command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd"); done
    if [ ${#missing[@]} -eq 0 ]; then echo "[deps] all present: $*"; return 0; fi
    fam=$(bx_distro_family)
    echo "[deps] MISSING: ${missing[*]}   (distro family: $fam)"
    if [ "$(id -u)" -ne 0 ]; then
        echo "[deps] not running as root — cannot install. Install manually: ${missing[*]}"
        return 1
    fi
    ic=$(bx_pkg_install_cmd)
    if [ -z "$ic" ]; then
        echo "[deps] unknown package manager — install manually: ${missing[*]}"
        return 1
    fi
    for cmd in "${missing[@]}"; do pkgs+=("$(bx_pkg_for "$cmd" "$fam")"); done
    mapfile -t pkgs < <(printf '%s\n' "${pkgs[@]}" | sort -u)
    if [ "${BX_DEP_DRYRUN:-0}" = 1 ]; then
        echo "[deps] (dry-run) would install: ${pkgs[*]}   via: $ic"
        return 0
    fi
    echo "[deps] installing: ${pkgs[*]}   via: $ic"
    # shellcheck disable=SC2086
    if ! eval "$ic ${pkgs[*]}"; then
        echo "[deps] ERROR: package install failed for: ${pkgs[*]}"
        return 1
    fi
    for cmd in "${missing[@]}"; do command -v "$cmd" >/dev/null 2>&1 || still+=("$cmd"); done
    if [ ${#still[@]} -ne 0 ]; then
        echo "[deps] ERROR: still missing after install: ${still[*]}"
        return 1
    fi
    echo "[deps] installed OK: ${pkgs[*]}"
    return 0
}
